blank_issues_enabled: true

contact_links:
  - name: Matrix community
    url: https://matrix.to/#/#atmachine-neovim:matrix.org
    about: Ask and discuss about LunarVim on Matrix.
  - name: Discord community
    url: https://discord.com/invite/sbDcEmJHww
    about: Ask and discuss about LunarVim on Discord.
